websample/Controllers/FormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace websample.Controllers
{
    public class FormController : Controller
    {
        // GET: Form
        public ActionResult Test1()
        {
            ViewBag.SelectOptions = new SelectListItem[] {
                new SelectListItem() { Value="0", Text="----" },
                new SelectListItem() { Value="2016", Text="平成28年" },
                new SelectListItem() { Value="2017", Text="平成29年" },
                new SelectListItem() { Value="2018", Text="平成30年" },
                new SelectListItem() { Value="2019", Text="平成31年" },
            };

            return View();
        }
        // GET: test1

        public class ReqRes
        {
            public string res { set; get; }
            public string kana { set; get; }
            public string alpha { set; get; }
            public string type { set; get; }
            public string ym { set; get; }
            public string yy { set; get; }
            public string memo { set; get; }

        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult sendback(ReqRes req)
        {
            req.res = "OK";

            return Json(req);
        }
    }
}

websample/Controllers/MenuController.cs
using System.Drawing.Printing;
using System.Web.Mvc;
using TuesPechkin;

namespace websample.Controllers
{
    using StringEx;

    public class MenuController : Controller
    {
        // GET: home
        public ActionResult Index()
        {
            string s = "";
            ViewBag.Title = s.JapaneseNumber();

            return View();
        }

    }

}

websample/Controllers/usersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.VisualBasic;
using websample.Models;

namespace websample.Controllers
{
    public class usersController : Controller
    {
        private testEntities db = new testEntities();

        // GET: users
        public ActionResult Index()
        {
            return View(db.users.ToList());
        }

        // GET: users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            user users = db.users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // GET: users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
//        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,kana,tel,password")] user users)
        {
            if (ModelState.IsValid)
            {
                db.users.Add(users);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(users);
        }

        // GET: users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            user users = db.users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // POST: users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
//        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,kana,tel,password")] user users)
        {
            if (ModelState.IsValid)
            {
                db.Entry(users).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(users);
        }

        // GET: users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            user users = db.users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // POST: users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            user users = db.users.Find(id);
            db.users.Remove(users);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

		public class ApiReq
		{
			public string cmd { get; set; }
			public string res { get; set; }
			public int id { get; set; }
			public user user { get; set; }
		}

        public class userres 
        {
            public int id { get; set; }
            public int name { get; set; }
        }
		public class ApiRes
		{
			public string res { get; set; } = "OK";
			public string msg { get; set; }
			public object users { get; set; }
			public user user { get; set; }

		}
		public ActionResult Api(ApiReq req)
		{
			var res = new ApiRes();
			switch (req.cmd)
			{
				case "LIST":
                    var u = new SampleModel();
                    res.users = u.GetUsers();
                    break ;

				case "SELECT":
					{
						user users = db.users.Find(req.id);
						if (users == null)
						{
							res.res = "NG";
						}
						else
						{
							res.user = users;
						}
						break;
					}

				case "UPDATE":
					if (!ModelState.IsValid)
					{
						res.res = "NG";
					}
					else
					{
						db.Entry(req.user).State = EntityState.Modified;
						try
						{
							db.SaveChanges();
						}
						catch (Exception e)
						{
							res.res = "NG";
							res.msg = e.ToString();
						}
					}
					break;

				case "INSERT":
					if (ModelState.IsValid)
					{
						db.users.Add(req.user);
						try
						{
							db.SaveChanges();
						}
						catch (Exception e)
						{
							res.res = "NG";
							res.msg = e.ToString();
						}
					}
					break;

				default:
					res.res = "NG";
					res.msg = "Bad Request";
					break;
			}
			return Json(res);

		}
		protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

websample/Views/Menu/Index.cshtml
@{
}

<h2>Index</h2>

<table>
    <tr>
        <td>
            @Html.ActionLink("フォーム入力その１", "test1", "Form", null, new { @class = "menu-btn" })
        </td>
    </tr>
    <tr>
        <td>
            @Html.ActionLink("ユーザー登録", "index", "users", null, new { @class = "menu-btn" })
        </td>
    </tr>
    <tr>
        <td>
            <button id="test1">テスト１</button>
        </td>
    </tr>
    <tr>
        <td>
            @Html.ActionLink("PDF", "index", "pdf", null, new { @class = "menu-btn" })
        </td>
    </tr>
    <tr>
        <td>
            @Html.TextBox("yearmonth", "", new {@class="ym"})
        </td>
        <td>
            @Html.TextBox("yearmonth", "", new { @class = "ym"})
        </td>
    </tr>
</table>

<div id="dlg_test">
    @Html.TextBox("yearmonth", "", new { @class = "ym" })

</div>

<div id="dlg_test2">
    @Html.TextBox("yearmonth", "", new { @class = "ym" })

</div>

websample/Views/Menu/test1.cshtml
@{
    ViewBag.Title = "test1";
}

<h2>test1</h2>

<table id="test1">
    <tr>
        <th>
        全角ひらがなを半角カナ
        </th>
        <td>
            <input type="text" class="in-item fhconvert" tabindex="1"  name="kana"/>
        </td>
    </tr>
    <tr>
        <th>
        全角英数を半角英数
        </th><td>
            <input type="text" class="in-item fhconvert" tabindex="2" data-fhconvert='ftoh' name="alpha"/>
        </td>
    </tr>
    <tr>
        <th>
            ラジオ
        </th>
        <td>
            <input type="radio" class ="in-item" tabindex="3" name="type" value="100" default checked>選択１
            <input type="radio" class ="in-item" tabindex="3" name="type" value="200">選択２
            <input type="radio" class ="in-item" tabindex="3" name="type" value="300">選択３
        </td>
    </tr>
    <tr>
        <th>
            年月選択
        </th>
        <td>
            <input type="text" class="in-item" tabindex="4" name="ym" />
        </td>
    </tr>
    <tr>
        <th>
            年選択
        </th>
        <td>
            @Html.DropDownList("yy", (IEnumerable<SelectListItem>)ViewBag.SelectOptions, new { @class = "in-item hoge" })
        </td>
    </tr>
    <tr>
        <th>
        </th>
        <td>
            <textarea class="in-item" name="memo"></textarea>
        </td>
    </tr>
    <tr>
        <th></th>
        <td>
            <button id="send">送信</button>
            <button id="pdf">PDF</button>
        </td>
    </tr>
</table>

<table id="test2">
    <tr>
        <th>
            全角ひらがなを半角カナ
        </th>
        <td>
            <input type="text" class="in-item fhconvert" tabindex="1" name="kana" />
        </td>
    </tr>
    <tr>
        <th>test</th>
        <td>
            @Html.ActionLink("送信２", "sendback", null, new { @class = "", @id = "send2", onclick = "return false;" })
        </td>
    </tr>
</table>